[[news]]
date = "2026-05"
content = "Updated this homepage with education, research experience, and accepted publications."

[[news]]
date = "2026-09"
content = "Incoming Ph.D. student in Machine Learning at Mohamed bin Zayed University of Artificial Intelligence (MBZUAI)."

[[news]]
date = "2025-05"
content = "Started an algorithm engineering internship at Alibaba Group, focusing on generative LTV prediction and confirmed GMV forecasting."
